# Generated by Django 4.2.11 on 2024-04-17 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('NC', 'New Connection'), ('BI', 'Billing Issue'), ('LC', 'Leakage Complaint'), ('OT', 'Other')], max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IP', 'In Progress'), ('RE', 'Resolved')], max_length=2)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('note', models.TextField()),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_requests.servicerequest')),
            ],
        ),
    ]
