# Generated by Django 4.2.11 on 2024-04-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
